accelerate launch \
    --config_file scripts/accelerate_configs/deepspeed_zero2_config.yaml \
    outdreamer/train/train_videoOutpaint_diffusers.py \
    --model OpenSoraCNext-ROPE-L/122 \
    --text_encoder_name google/mt5-xxl \
    --cache_dir "./cache_dir" \
    --dataset t2v \
    --data "scripts/train_data/data_pexels.txt" \
    --ae CausalVAEModel_D4_4x8x8 \
    --ae_path "/path/to/vae" \
    --sample_rate 1 \
    --num_frames 29 \
    --max_height 480 \
    --max_width 640 \
    --interpolation_scale_t 1.0 \
    --interpolation_scale_h 1.0 \
    --interpolation_scale_w 1.0 \
    --attention_mode xformers \
    --gradient_checkpointing \
    --train_batch_size=1 \
    --dataloader_num_workers 10 \
    --gradient_accumulation_steps=1 \
    --max_train_steps=10000 \
    --learning_rate=2e-5 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=0 \
    --mixed_precision="bf16" \
    --report_to="wandb" \
    --pretrained "/path/to/pretrained-model" \
    --checkpoints_total_limit 30 \
    --checkpointing_steps 1000 \
    --resume_from_checkpoint="latest" \
    --allow_tf32 \
    --model_max_length 512 \
    --use_image_num 0 \
    --tile_overlap_factor 0.125 \
    --snr_gamma 5.0 \
    --use_ema \
    --ema_start_step 0 \
    --cfg 0.1 \
    --noise_offset 0.02 \
    --use_rope \
    --ema_decay 0.999 \
    --enable_tiling \
    --speed_factor 1.0 \
    --group_frame \
    --output_dir="/path/to/output" \
    --given_frame_max_num 3